### PR TITLE
Changes for build automation

### PR DESCRIPTION
**Pull request by email4rohit**
Changes for build automation to be made available at https://tuxgold.corp.microsoft.com/job/MFA

Summary of Changes - 

*  Changed android-support version from '[18,)' to 'r7'
*  Added required jars in src/lib
*  Added code to look for jars in src/lib
*  Changed groupId for support-v4.jar from 'com.android.support' to 'com.google.android'
*  Changed buildSourceEncoding to ISO-8859-1

Testing - 

* Verified that jenkins(on tuxgold) can build from pom.xml and added jars.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-android/pull/345%23issuecomment-74967684%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-android/pull/345%23issuecomment-75336641%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-android/pull/345%23issuecomment-75339685%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-android/pull/345%23issuecomment-74967684%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22We%20don%27t%20keep%20jars%20inside%20the%20repo.%20You%20can%20use%20this%20script%20to%20do%20jenkins%20build%3A%5Cr%5Cn%5Cr%5Cnrem%20Call%20this%20from%20jenkins%20build%20step%20%5Cr%5Cn%20%5Cr%5Cnrem%20setup%20local%20maven%20repo%20to%20use%20for%20this%20build%5Cr%5Cnset%20REPOROOT%3D%25%7Edp0%5Cr%5Cnset%20REPOROOT%3D%25REPOROOT%3A%7E0%2C-1%25%5Cr%5Cnset%20MAVENREPO%3DD%3A%5C%5Cconfig%5C%5CLocalMavenRepo%5Cr%5Cn%5Cr%5Cnmd%20%25MAVENREPO%25%5Cr%5Cndel%20/q%20%25MAVENREPO%25%5C%5C%2A.%2A%5Cr%5Cn%5Cr%5Cnecho%20%5C%22Get%20support%20library%20into%20m2%20repo%20for%20android%5C%22%5Cr%5Cngit%20clone%20https%3A//github.com/mosabua/maven-android-sdk-deployer.git%5Cr%5Cncd%20maven-android-sdk-deployer/platforms/android-18%5Cr%5Cncall%20mvn%20clean%20install%20--quiet%20-Dmaven.repo.local%3D%25MAVENREPO%25%5Cr%5Cncd%20../../extras/compatibility-v4%5Cr%5Cncall%20mvn%20clean%20install%20-Dextras.compatibility.v4.groupid%3Dcom.android.support%20-Dextras.compatibility.v4.artifactid%3Dsupport-v4%20-Dmaven.repo.local%3D%25MAVENREPO%25%5Cr%5Cncd%20../../../%5Cr%5Cn%5Cr%5Cnrem%20build%20adal%5Cr%5Cnmvn%20clean%20install%20--quiet%20-Dmaven.repo.local%3D%25MAVENREPO%25%5Cr%5Cn%5Cr%5Cn%40echo%20%3D%5Cr%5Cnecho%20%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cr%5Cnecho%20DONE%22%2C%20%22created_at%22%3A%20%222015-02-18T23%3A03%3A44Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/466805%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/omercs%22%7D%7D%2C%20%7B%22body%22%3A%20%22-%20I%20have%20removed%20the%20checked-in%20jars%20and%20used%20maven-android-sdk-deployer%20to%20get%20all%20the%20dependencies.%22%2C%20%22created_at%22%3A%20%222015-02-20T23%3A11%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6364688%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/email4rohit%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222015-02-20T23%3A38%3A56Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6364688%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/email4rohit%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/345#issuecomment-74967684'>General Comment</a></b>
- <a href='https://github.com/omercs'></a> We don't keep jars inside the repo. You can use this script to do jenkins build:
rem Call this from jenkins build step
rem setup local maven repo to use for this build
set REPOROOT=%~dp0
set REPOROOT=%REPOROOT:~0,-1%
set MAVENREPO=D:\config\LocalMavenRepo
md %MAVENREPO%
del /q %MAVENREPO%\*.*
echo "Get support library into m2 repo for android"
git clone https://github.com/mosabua/maven-android-sdk-deployer.git
cd maven-android-sdk-deployer/platforms/android-18
call mvn clean install --quiet -Dmaven.repo.local=%MAVENREPO%
cd ../../extras/compatibility-v4
call mvn clean install -Dextras.compatibility.v4.groupid=com.android.support -Dextras.compatibility.v4.artifactid=support-v4 -Dmaven.repo.local=%MAVENREPO%
cd ../../../
rem build adal
mvn clean install --quiet -Dmaven.repo.local=%MAVENREPO%
@echo =
echo ==========================
echo DONE
- <a href='https://github.com/email4rohit'></a> - I have removed the checked-in jars and used maven-android-sdk-deployer to get all the dependencies.

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-android/pull/345?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-android/pull/345?approve=1'></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/345'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by RandalliLama** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/345'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by omercs** [comment]
We don't keep jars inside the repo. You can use this script to do jenkins build:

rem Call this from jenkins build step 
 
rem setup local maven repo to use for this build
set REPOROOT=%~dp0
set REPOROOT=%REPOROOT:~0,-1%
set MAVENREPO=D:\config\LocalMavenRepo

md %MAVENREPO%
del /q %MAVENREPO%\*.*

echo "Get support library into m2 repo for android"
git clone https://github.com/mosabua/maven-android-sdk-deployer.git
cd maven-android-sdk-deployer/platforms/android-18
call mvn clean install --quiet -Dmaven.repo.local=%MAVENREPO%
cd ../../extras/compatibility-v4
call mvn clean install -Dextras.compatibility.v4.groupid=com.android.support -Dextras.compatibility.v4.artifactid=support-v4 -Dmaven.repo.local=%MAVENREPO%
cd ../../../

rem build adal
mvn clean install --quiet -Dmaven.repo.local=%MAVENREPO%

@echo =
echo ==========================
echo DONE

**Comment by email4rohit** [comment]
- I have removed the checked-in jars and used maven-android-sdk-deployer to get all the dependencies.

**Comment by email4rohit** [comment]
:+1:

**Comment by omercs** [comment]
Closing this since we accept to dev branch.

**Pull request closed without merging**
