### PR TITLE
Dev Loyalty: Survey link added to README.md

### PR DESCRIPTION
**Pull request by ShannonCanTech**
Developer loyalty survey link added to README.md.

Added library-specific quick-links to top of README.md for unified look/access across all of ADAL libraries and sample as I add survey links to each of them. This survey can be voluntarily and anonymously submitted by developers and will be used to understand migration processes for the upcoming deprecation. We will also gain insights into CES and CVA for all users who submit the form. ADAL SDK for Android form: 

https://forms.office.com/r/Xx9tB8g8R4
--

image
image

### CODE REVIEW

**Comment by ShannonCanTech** [comment]
Hi @iambmelt, can this be merged in? @Om83

**Comment by iambmelt** [comment]
> Hi @iambmelt, can this be merged in? @Om83

Let me sync on this with team in our scrum and get back to you this week

**Comment by ShannonCanTech** [comment]
> > Hi @iambmelt, can this be merged in? @Om83
> 
> Let me sync on this with team in our scrum and get back to you this week

This and the ADAL Ruby library are the last PRs needed to be merged with survey link n README.md file. Would you also mind mentioning that and MSAL Objc and MSAL Android README.md update as well? Here's current list of all PRs submitted. 
| Library | Status | PR Link |
| --- | --- | --- |
| ADAL Objc | Merged | https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/1568 |
| ADAL Ruby | Abandoned Repo? | https://github.com/AzureAD/azure-activedirectory-library-for-ruby/pull/70 |
| ADAL Android | Awaiting review | https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/1590 |
| ADAL .NET | Merged | https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1723 |
| ADAL.js | Merged | https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/928 |
| ADAL Python | Merged | https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/249 |
| ADAL NodeJS | Merged | https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/pull/254 |
| ADAL Java | Merged | https://github.com/AzureAD/azure-activedirectory-library-for-java/pull/304 |
| MSAL Android | Locating reviewers | https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1353 |
| MSAL Objc | Awaiting final review | https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/1287 |
| MSAL Java | Merged | https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/369 |
| MSAL Python | Merged | https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/340 |
| MSAL Go | Merged | https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/204 |
| MSAL.js | Merged | https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/3397 |
MSAL .NET | Merged | https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2531 |

Ping me on Teams if you have any questions.

**Review by iambmelt — APPROVED** [review]

**Comment by iambmelt** [comment]
> > > Hi @iambmelt, can this be merged in? @Om83
> > 
> > 
> > Let me sync on this with team in our scrum and get back to you this week
> 
> This and the ADAL Ruby library are the last PRs needed to be merged with survey link n README.md file. Would you also mind mentioning that and MSAL Objc and MSAL Android README.md update as well? Here's current list of all PRs submitted.
> 
> Library	Status	PR Link
> ADAL Objc	Merged	[AzureAD/azure-activedirectory-library-for-objc#1568](https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/1568)
> ADAL Ruby	Abandoned Repo?	[AzureAD/azure-activedirectory-library-for-ruby#70](https://github.com/AzureAD/azure-activedirectory-library-for-ruby/pull/70)
> ADAL Android	Awaiting review	#1590
> ADAL .NET	Merged	[AzureAD/azure-activedirectory-library-for-dotnet#1723](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1723)
> ADAL.js	Merged	[AzureAD/azure-activedirectory-library-for-js#928](https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/928)
> ADAL Python	Merged	[AzureAD/azure-activedirectory-library-for-python#249](https://github.com/AzureAD/azure-activedirectory-library-for-python/pull/249)
> ADAL NodeJS	Merged	[AzureAD/azure-activedirectory-library-for-nodejs#254](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/pull/254)
> ADAL Java	Merged	[AzureAD/azure-activedirectory-library-for-java#304](https://github.com/AzureAD/azure-activedirectory-library-for-java/pull/304)
> MSAL Android	Locating reviewers	[AzureAD/microsoft-authentication-library-for-android#1353](https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1353)
> MSAL Objc	Awaiting final review	[AzureAD/microsoft-authentication-library-for-objc#1287](https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/1287)
> MSAL Java	Merged	[AzureAD/microsoft-authentication-library-for-java#369](https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/369)
> MSAL Python	Merged	[AzureAD/microsoft-authentication-library-for-python#340](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/340)
> MSAL Go	Merged	[AzureAD/microsoft-authentication-library-for-go#204](https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/204)
> MSAL.js	3/6 reviewers approved. Awaiting review *	[AzureAD/microsoft-authentication-library-for-js#3397](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/3397)
> MSAL .NET	Merged	[AzureAD/microsoft-authentication-library-for-dotnet#2531](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2531)
> Ping me on Teams if you have any questions.

Our team owns only the Android repos in this list; as such, you'll need to reach out to the maintainers of those libraries to get their approval. Feel free to send me an email or Teams msg if you are unsure of whom you should be in contact with

I took the step to go ahead and merge your two PRs for ADAL/MSAL Android

**Pull request merged**
