### PR TITLE
Update Gradle Version and SdkVersion to last version 28 (Pie)Update 

### PR DESCRIPTION
**Pull request by carlosgub**
Update supportLibraryVersion to last version 28.0.0
Update gradleVersion to last version
Update targetSdkVersion to last version 28 (Pie)
Update compileSdkVersion to last version 28 (Pie)
Cheers #Hacktoberfest

### CODE REVIEW

**Comment by carlosgub** [comment]
Hi, the problem from travis-ci is 

> To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html

The solution I suppose is accept to download the new SDK.

Cheers #Hacktoberfest

**Comment by carlosgub** [comment]
@iambmelt I do today w8 my PR 😇

**Comment by carlosgub** [comment]
Now I have this problem, I dont know why this happens 😢 , @iambmelt can you help me :D ?

`Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;27.0.3 Android SDK Build-Tools 27.0.3
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html`

**Comment by iambmelt** [comment]
@carlosgub -- I took a look at this, and it looks like we won't be able to accept this change [yet!] due to some of the deprecations in API 28+ 😢 

Mainly, our tests have not yet migrated to the [Android Testing Support Library](https://developer.android.com/training/testing/) -- as a result, I cannot compile our tests [much less run them!] when updating to the latest tools. Technical debt, I'm afraid :(

For reference, most of the problems seem centered around a few classes
- `UiThreadTest`
- `RenamingDelegatingContext`
- `MockContentProvider`
- `MockContentResolver`
- `MockContext`
- `MockPackageManager`

I'm going to close this PR for now, as I unfortunately don't have the cycles right now to re-tool our tests. Nevertheless, thank you for your contribution and we look forward to seeing you around ADAL (or our shiny new repo, [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-android)!).

Cheers

**Pull request closed without merging**
