### PR TITLE
Debugged lint errors

### PR DESCRIPTION
**Pull request by heidijinxujia**
1. fix the error that the string variables cannot be translated in other language
2. fix the error that the string variables cannot be found in the default locale

### CODE REVIEW

**Comment by weijjia** [comment]
Are you merging changes from dev to master?

**Comment by heidijinxujia** [comment]
No, I didn’t.

**Comment by heidijinxujia** [comment]
I am trying to do the mvn compile thing.

**Comment by weijjia** [comment]
what are you trying to do with PR? why we want to merge from dev to master?

**Comment by heidijinxujia** [comment]
I'm not sure how to fix the commit path here.

**Pull request closed without merging**
