### PR TITLE
Petterh/issue 726: Do not treat web view errors as "cancel"

### PR DESCRIPTION
**Pull request by petterh**
This fixes [issue 726: Web view errors treated as cancel](https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/726).

This change properly propagates server-side authentication errors to client instead of pretending the user cancelled the flow.

Other minor fixes include removal of trailing white space, fixing the occasional typo and protecting against a possible NRE in `Discovery`.

### CODE REVIEW

**Comment by petterh** [comment]
@iambmelt Any chance of anyone reviewing this? It's been over a year since I created the PR, but the bug is still there.

**Comment by iambmelt** [comment]
Hi @petterh -- thanks for updating your PR -- personally, I'd really like to see this merge but am heads-down on some other work before I can dedicate cycles to this. This item has recently moved up visibility-wise and will be prioritized in an upcoming planning meeting.

**Comment by petterh** [comment]
@iambmelt @heidijinxujia Any chance of this ever getting in? It's been hanging for over 22 months now.

**Comment by iambmelt** [comment]
@petterh Merged - thanks for nudge :-)

**Pull request merged**
