### PR TITLE
Closes #384 & Updates REAME.md for current mvn central deploys

### LINKED ISSUE #384: Gradle example reports gson vs. support lib dependencies inconsistently
The dependencies declared (below) work if the user's app already declares a dependency on android.support - but this isn't said explicitly which might confuse someone new to Android and developing on the lastest SDKs

    dependencies {
        compile('com.microsoft.aad:adal:1.1.1') { 
            exclude group: 'com.android.support'
        }
    }

So we could either

    dependencies {
        compile('com.microsoft.aad:adal:1.1.1')
    }

or 

    dependencies {
        compile('com.microsoft.aad:adal:1.1.1') { 
            exclude group: 'com.android.support'
            exclude group: 'com.google.code.gson'
        }
    }

or, what may be the most flexible, per d22fd632ac271a071ddbc56016d468ac1811113f

    dependencies {
        // your dependencies here...
        compile('com.microsoft.aad:adal:1.1.3') {
            // if your app includes android support
            // libraries or Gson in its dependencies
            // exclude that groupId from ADAL's compile
            // task by un-commenting the appropriate
            // line below

           // exclude group: 'com.android.support'
           // exclude group: 'com.google.code.gson'
    }
}

### PR DESCRIPTION
**Pull request by iambmelt**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-android/pull/385%23issuecomment-103116970%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-android/pull/385%23issuecomment-103120197%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-android/pull/385%23issuecomment-103144153%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-android/pull/385%23issuecomment-103116970%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20__%40iambmelt__%2C%20I%27m%20your%20friendly%20neighborhood%20Microsoft%20Open%20Technologies%2C%20Inc.%20Pull%20Request%20Bot%20%28You%20can%20call%20me%20MSOTBOT%29.%20Thanks%20for%20your%20contribution%21%5Cr%5Cn%20%20%20%20%3Cspan%3E%5Cr%5Cn%20%20%20%20%20%20%20%20This%20seems%20like%20a%20small%20%28but%20important%29%20contribution%2C%20so%20no%20Contribution%20License%20Agreement%20is%20required%20at%20this%20point.%20Real%20humans%20will%20now%20evaluate%20your%20PR.%5Cr%5Cn%20%20%20%20%3C/span%3E%5Cr%5Cn%5Cr%5CnTTYL%2C%20MSOTBOT%3B%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-05-18T16%3A17%3A01Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9519461%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/msotclas%22%7D%7D%2C%20%7B%22body%22%3A%20%22Appears%20that%20the%20emulator%20failed%20to%20start%20in%20CI%20-%20don%27t%20see%20how%20this%20could%20relate%20to%20a%20readme%20change.%22%2C%20%22created_at%22%3A%20%222015-05-18T16%3A32%3A45Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/990063%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/iambmelt%22%7D%7D%2C%20%7B%22body%22%3A%20%22Hi%20__%40iambmelt__%2C%20I%27m%20your%20friendly%20neighborhood%20Microsoft%20Open%20Technologies%2C%20Inc.%20Pull%20Request%20Bot%20%28You%20can%20call%20me%20MSOTBOT%29.%20Thanks%20for%20your%20contribution%21%5Cr%5Cn%20%20%20%20%3Cspan%3E%5Cr%5Cn%20%20%20%20%20%20%20%20This%20seems%20like%20a%20small%20%28but%20important%29%20contribution%2C%20so%20no%20Contribution%20License%20Agreement%20is%20required%20at%20this%20point.%20Real%20humans%20will%20now%20evaluate%20your%20PR.%5Cr%5Cn%20%20%20%20%3C/span%3E%5Cr%5Cn%5Cr%5CnTTYL%2C%20MSOTBOT%3B%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-05-18T17%3A36%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9519461%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/msotclas%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/385#issuecomment-103116970'>General Comment</a></b>
- <a href='https://github.com/msotclas'></a> Hi __@iambmelt__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
<span>
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
</span>
TTYL, MSOTBOT;
- <a href='https://github.com/iambmelt'></a> Appears that the emulator failed to start in CI - don't see how this could relate to a readme change.
- <a href='https://github.com/msotclas'></a> Hi __@iambmelt__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
<span>
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
</span>
TTYL, MSOTBOT;

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-android/pull/385?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-android/pull/385?approve=1'></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/385'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by RandalliLama** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/385'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by msotclas** [comment]
Hi __@iambmelt__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSOTBOT;

**Comment by iambmelt** [comment]
Appears that the emulator failed to start in CI - don't see how this could relate to a readme change.

**Comment by msotclas** [comment]
Hi __@iambmelt__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSOTBOT;

**Pull request merged**
