### PR TITLE
Removes failing assertion for Authority Migration (no network mock, nondeterministic)

### PR DESCRIPTION
**Pull request by iambmelt**
Builds are failing due to unit test failure - this test is passing locally. This branch is to troubleshoot

### CODE REVIEW

**Comment by iambmelt** [comment]
Tests now passing in CI but failing locally... Not an acceptable solution.

**Comment by iambmelt** [comment]
Testing builds of #1001 (Reverts all PRs merged on 10/18) - build continues to fail.

**Comment by heidijinxujia** [comment]
Hi @iambmelt  Is it for release branch only? Are you going to open another PR or update it later to add the network mock?

**Comment by iambmelt** [comment]
@heidijinxujia Assertion to be commented-out on `release` - will file `P1` issue for `dev`

**Pull request closed without merging**
