### PR TITLE
Clean up the tabs and unnecessary comments in the code

### PR DESCRIPTION
**Pull request by heidijinxujia**
#636 
- clean the tabs
- clean the comment
- format the code

### CODE REVIEW

**Comment by weijjia** [comment]
I'm just curious, do you run a auto-format on all the files?

**Comment by heidijinxujia** [comment]
@weijjia  Yes, for the tabs and javadoc I run the auto-format. And I need this PR to be merged if there is no another problem. Because I do not want the tabs reappear in Android Studio. Thank you.

**Comment by weijjia** [comment]
As I mentioned today in the standup, tab changes can cause a lot of merging conflicts. I don't understand why we cannot put it along with the android studio merging.

**Comment by heidijinxujia** [comment]
OK. I will move it to android studio.

**Comment by RandalliLama** [comment]
@heidijinxujia Should we close this PR then?

**Pull request closed without merging**
