### PR TITLE
Update Gson to 2.8.0

### LINKED ISSUE #838: Upgrade GSON to 2.8.0 (latest)
Can we please make sure to keep the libraries updated in this library, such as GSON? https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/build.gradle#L85

Latest is 2.8.0: https://mvnrepository.com/artifact/com.google.code.gson/gson/2.8.0

### PR DESCRIPTION
**Pull request by jaredsburrows**
@addev-ashish 
Closes #838.

### CODE REVIEW

**Comment by jaredsburrows** [comment]
@weijjia Why would you downvote this?

**Comment by weijjia** [comment]
Sorry, it was by accident.

**Comment by jaredsburrows** [comment]
@weijjia Haha. Awesome! Thanks for approving the PR!

**Comment by jaredsburrows** [comment]
Can we merge this please?

**Comment by heidijinxujia** [comment]
@nazukj I've run the VSTS CI for this PR. It is all green. I think it is ready to merge. (https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/844)

**Comment by jaredsburrows** [comment]
Thanks!

**Comment by heidijinxujia** [comment]
@jaredsburrows Thank you for your contribution to ADAL. We were facing an issue to trigger the VSTS for forked PR. Please feel free the merge your PR once all checks green. Thanks. :)

**Comment by jaredsburrows** [comment]
@nazukj @heidijinxujia I am not a member of this repository. Can you add me? I cannot merge this, you will have to, please.

**Comment by heidijinxujia** [comment]
Hi @jaredsburrows I will merge the PR once all VSO issues are resolved. Thank you!

**Comment by jaredsburrows** [comment]
@heidijinxujia Thank you!

**Comment by jaredsburrows** [comment]
@weijjia @heidijinxujia @addev-ashish @nazukj Thank you all!

**Pull request merged**
