### PR TITLE
Updating gradle & Maven for 1.1.2 + using remote repo

### PR DESCRIPTION
**Pull request by iambmelt**
Updated Maven url to use the remote listed [here](https://maven-repository.com/artifact/com.microsoft.aad/adal/1.1.2).
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-android/pull/380%23issuecomment-100386443%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-android/pull/380%23issuecomment-101750300%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-android/pull/380%23issuecomment-101776211%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-android/pull/380%23issuecomment-100386443%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20__%40iambmelt__%2C%20I%27m%20your%20friendly%20neighborhood%20Microsoft%20Open%20Technologies%2C%20Inc.%20Pull%20Request%20Bot%20%28You%20can%20call%20me%20MSOTBOT%29.%20Thanks%20for%20your%20contribution%21%5Cr%5Cn%20%20%20%20%3Cspan%3E%5Cr%5Cn%20%20%20%20%20%20%20%20This%20seems%20like%20a%20small%20%28but%20important%29%20contribution%2C%20so%20no%20Contribution%20License%20Agreement%20is%20required%20at%20this%20point.%20Real%20humans%20will%20now%20evaluate%20your%20PR.%5Cr%5Cn%20%20%20%20%3C/span%3E%5Cr%5Cn%5Cr%5CnTTYL%2C%20MSOTBOT%3B%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-05-08T22%3A34%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9519461%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/msotclas%22%7D%7D%2C%20%7B%22body%22%3A%20%22Can%20you%20send%20the%20pull%20request%20to%20dev%20branch%3F%20%22%2C%20%22created_at%22%3A%20%222015-05-13T17%3A16%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/466805%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/omercs%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40omercs%20Can%20do%20-%20will%20also%20update%20this%20PR%20for%20the%20newly%20released%20%5B1.1.3%5D%28https%3A//maven-repository.com/artifact/com.microsoft.aad/adal/1.1.3%29%22%2C%20%22created_at%22%3A%20%222015-05-13T18%3A53%3A46Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/990063%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/iambmelt%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/380#issuecomment-100386443'>General Comment</a></b>
- <a href='https://github.com/msotclas'></a> Hi __@iambmelt__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
<span>
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
</span>
TTYL, MSOTBOT;
- <a href='https://github.com/omercs'></a> Can you send the pull request to dev branch?
- <a href='https://github.com/iambmelt'></a> @omercs Can do - will also update this PR for the newly released [1.1.3](https://maven-repository.com/artifact/com.microsoft.aad/adal/1.1.3)

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-android/pull/380?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-android/pull/380?approve=1'></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/380'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@iambmelt__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSOTBOT;

**Comment by omercs** [comment]
Can you send the pull request to dev branch?

**Comment by iambmelt** [comment]
@omercs Can do - will also update this PR for the newly released [1.1.3](https://maven-repository.com/artifact/com.microsoft.aad/adal/1.1.3)

**Comment by iambmelt** [comment]
@omercs closing this for now.

**Pull request closed without merging**
