### PR TITLE
Fix issue #410

### PR DESCRIPTION
**Pull request by heidijinxujia**
Correct the typo in all "challange" related files.

### CODE REVIEW

**Comment by heidijinxujia** [comment]
@weijjia Thanks!

**Comment by sdabbiru** [comment]
:shipit:

**Comment by imakhalova** [comment]
Update corresponding tests (in ChallangeResponseBuilderTests)

**Comment by weijjia** [comment]
+1 Please update corresponding tests. I'm going to revert the commit. @heidijinxujia

**Comment by heidijinxujia** [comment]
OK.

**Pull request merged**
