### PR TITLE
Fixes for README

### PR DESCRIPTION
**Pull request by iambmelt**
I'm targeting updating the prod docs (i.e. ```master```) - simplifying & genericizing the gradle config & rolling back what looks to be a dev-release dependency in the pom example. I'm not seeing ```1.1.5``` in [Maven Central](https://maven-repository.com/artifact/com.microsoft.aad/adal)
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-android/pull/383%23issuecomment-103097783%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-android/pull/383%23issuecomment-103101948%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-android/pull/383%23issuecomment-103109568%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-android/pull/383%23issuecomment-103110700%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-android/pull/383%23issuecomment-103097783%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20__%40iambmelt__%2C%20I%27m%20your%20friendly%20neighborhood%20Microsoft%20Open%20Technologies%2C%20Inc.%20Pull%20Request%20Bot%20%28You%20can%20call%20me%20MSOTBOT%29.%20Thanks%20for%20your%20contribution%21%5Cr%5Cn%20%20%20%20%3Cspan%3E%5Cr%5Cn%20%20%20%20%20%20%20%20This%20seems%20like%20a%20small%20%28but%20important%29%20contribution%2C%20so%20no%20Contribution%20License%20Agreement%20is%20required%20at%20this%20point.%20Real%20humans%20will%20now%20evaluate%20your%20PR.%5Cr%5Cn%20%20%20%20%3C/span%3E%5Cr%5Cn%5Cr%5CnTTYL%2C%20MSOTBOT%3B%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-05-18T15%3A21%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9519461%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/msotclas%22%7D%7D%2C%20%7B%22body%22%3A%20%22Strange%20to%20see%20%40omercs%20commits%20in%20my%20PR%20-%20I%20guess%20this%20is%20because%20I%20synced%20my%20fork%3F%20I%27m%20not%20clear%20on%20that.%22%2C%20%22created_at%22%3A%20%222015-05-18T15%3A25%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/990063%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/iambmelt%22%7D%7D%2C%20%7B%22body%22%3A%20%22You%20should%20sync%20your%20dev%20branch%20to%20dev%20branch%20here%20and%20then%20send%20your%20pull%20request.%20We%20should%20see%20the%20commits%20related%20to%20the%20file%20you%20are%20changing.%20You%20are%20sending%20merge%20commits%20from%20dev%20to%20master%20back%20to%20dev.%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-05-18T15%3A47%3A04Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/466805%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/omercs%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40omercs%20ah%20-%20yes.%20I%27ll%20resolve%20that.%20Thx.%20%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-05-18T15%3A50%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/990063%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/iambmelt%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/383#issuecomment-103097783'>General Comment</a></b>
- <a href='https://github.com/msotclas'></a> Hi __@iambmelt__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
<span>
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
</span>
TTYL, MSOTBOT;
- <a href='https://github.com/iambmelt'></a> Strange to see @omercs commits in my PR - I guess this is because I synced my fork? I'm not clear on that.
- <a href='https://github.com/omercs'></a> You should sync your dev branch to dev branch here and then send your pull request. We should see the commits related to the file you are changing. You are sending merge commits from dev to master back to dev.
- <a href='https://github.com/iambmelt'></a> @omercs ah - yes. I'll resolve that. Thx. :+1:

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-android/pull/383?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-android/pull/383?approve=1'></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/383'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by RandalliLama** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/383'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by msotclas** [comment]
Hi __@iambmelt__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSOTBOT;

**Comment by iambmelt** [comment]
Strange to see @omercs commits in my PR - I guess this is because I synced my fork? I'm not clear on that.

**Comment by omercs** [comment]
You should sync your dev branch to dev branch here and then send your pull request. We should see the commits related to the file you are changing. You are sending merge commits from dev to master back to dev.

**Comment by iambmelt** [comment]
@omercs ah - yes. I'll resolve that. Thx. :+1:

**Comment by iambmelt** [comment]
This PR is getting too noisy - will resubmit with something clean :)

**Pull request closed without merging**
