### PR TITLE
Removes dead code related to onReceive()

### PR DESCRIPTION
**Pull request by iambmelt**
See #868

Please note: commit bb3263998378dc29dabfd412dcdb2dd2d9e2f5d5 preserves public methods and variables exposed by ApplicationReceiver.

~~Changes outside of this will require a major version change.~~

### CODE REVIEW

**Comment by iambmelt** [comment]
Questions for code reviewers:
- `ApplicationReceiver` is a `public class`; do we have users who may be dependent on the following `public` fields/methods?
    * `ApplicationReceiver#saveRequest(Context, AuthenticationRequest, String)`
    * `ApplicationReceiver#getUserName(Context)`
    * `ApplicationReceiver#getInstallRequestInThisApp(Context)`
    * `ApplicationReceiver#clearUserName(Context)`
    * `ApplicationReceiver#INSTALL_REQUEST_TRACK_FILE`
    * `ApplicationReceiver#INSTALL_REQUEST_TRACK_KEY`
    * `ApplicationReceiver#INSTALL_REQUEST_TIME_STAMP`
    * `ApplicationReceiver#INSTALL_URL_KEY`
- Are we still relying on the functionality within [this branch](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/main/java/com/microsoft/aad/adal/BasicWebViewClient.java#L264-L284)?
    * Functionality appears to still be in use. Unclear who may rely on data stored by `ApplicationReceiver#saveRequest(Context, AuthenticationRequest, String)`
- Can [this test](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/androidTest/java/com/microsoft/aad/adal/AuthenticationActivityUnitTest.java#L172-L204) be deleted entirely?
    * If public API for `ApplicationReceiver` isn't going to change, this test remains valid. Otherwise, good candidate for deletion.

**Comment by iambmelt** [comment]
@addev-ashish 

Deleting this class would remove a public class from the API. -- wouldn't this by definition force us to make a major version change?

Regarding deleting the entire file, would you expect the functionality of [this branch](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/main/java/com/microsoft/aad/adal/BasicWebViewClient.java#L264-L284) to be preserved? Or would the contained call to [`saveRequest()`](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/main/java/com/microsoft/aad/adal/BasicWebViewClient.java#L266) be removed with all the other functionality left intact? It sticks data in `SharedPreferences` -- not clear to me who might be reading this (partner apps, etc)

**Comment by iambmelt** [comment]
Per conversation in scrum - will remove entire file; not going to major rev.

**Comment by iambmelt** [comment]
To do:
- Test MAM-CA flow

**Comment by iambmelt** [comment]
Tested and working as expected

**Comment by weijjia** [comment]
@iambmelt @addev-ashish we should also remove this part https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/main/java/com/microsoft/aad/adal/AcquireTokenRequest.java#L794?

**Pull request merged**
