### PR TITLE
Update Gradle to 4.1

### PR DESCRIPTION
**Pull request by jaredsburrows**
- Update Android Gradle Plugin to 2.3.3
- Update Gradle to 4.1

### CODE REVIEW

**Comment by jaredsburrows** [comment]
Pmd was most likely updated. Let me take a look.

**Comment by jaredsburrows** [comment]
@iambmelt Should be good to go now!

**Comment by jaredsburrows** [comment]
Thanks.

**Comment by iambmelt** [comment]
Invalidated by https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/1242

**Pull request closed without merging**
