### PR TITLE
Fix for failing unit tests

### PR DESCRIPTION
**Pull request by heidijinxujia**
There are two failing tests.
- testKeyPair()
    Filed on issue #580. The failing is caused by the secretKey setting in the setup which caused the conflict when loadSecretKeyForEncryption(). It is expected to return null from AuthenticationSettings.INSTANCE.getSecretKeyData() and created the key pair by calling generateKeyPairFromAndroidKeyStore().
- testCreateFromResourceUrlInvalidFormat()
    The fail is caused by the network connection, the test passed when the test device is connected to WiFi. And get failed otherwise. The fix is to add the HTTP response mocking.

### CODE REVIEW

**Comment by addev-ashish** [comment]
please add a better description to the PR.

**Comment by weijjia** [comment]
ah, i think we should suppress the tests.

**Comment by addev-ashish** [comment]
fix the branch warning above then :shipit:

**Comment by heidijinxujia** [comment]
@HSAR @addev-ashish added you guys into the reviewers, please approve the PR. Then I can merge it.

**Comment by HSAR** [comment]
CI now failing.

**Comment by HSAR** [comment]
testKeyPair is now failing again.

**Comment by weijjia** [comment]
you need to add the suppress annotation.

**Comment by weijjia** [comment]
@heidijinxujia suppress is not deleting the test. Can you add @Suppress annotation?

**Comment by HSAR** [comment]
If you are deciding to delete or ignore a test, be sure to make a note in the relevant work item or test case explaining why.

**Comment by heidijinxujia** [comment]
Moved to another PR. Because the commits cannot be squashed.

**Pull request closed without merging**
